### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by themihai** [oleksandr/bonjour#16]
Is this project dead?

**Comment by oleksandr** [comment]
Kind of. I'm out of time and work in a completely different domain now.
Gladly would transfer the project to anyone interested.

**Comment by rdeg** [comment]
As an alternative, one can use the zeroconf package that can be found at 
[https://github.com/grandcat/zeroconf](url)
It has been inspired by oleksandr's bonjour, works pretty well and is currently active.
